pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('AZ')

    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        
       
        stage('ACR Build &  Push') {
            steps {
		//sh 'docker push raj80dockerid/jenkinstest' (this will use the tag latest)    
                sh 'acr_name = $(az acr list --resource-group vinex22 --query [0].name -o tsv)' 
                sh 'az acr build -t vinex22/pythontest:$BUILD_NUMBER -r $ACR_Name ./pushdockerimageAZ/'
                }
            }
        }
    post {
		always {
			sh 'echo "Build Sucessfull"'
		}
	 }
    }

